FROM quay.io/feedyard/buildkite-remote-docker:0.2.0

LABEL maintainer=<nic.cheneweth@thoughtworks.com>

# package versions installed
ENV SETUPTOOLS_VERSION=41.4.0
ENV INSPEC_VERSION=4.18.0
ENV INVOKE_VERSION=1.3.0
ENV PYLINT_VERSION=2.4.2
ENV YAMLLINT_VERSION=1.18.0
ENV HADOLINT_VERSION=1.17.2

RUN apk add --no-cache \
        openrc \
        docker \
        python3 \
        ruby \
        ruby-bundler \
        ruby-bigdecimal \
        ruby-webrick \
        gnupg \
        jq && \
    apk --no-cache add --virtual build-dependencies \
        build-base \
        python3-dev \
        ruby-dev \
        libffi-dev \
        musl-dev \
        g++ \
        gcc \
        make && \
        rc-update add docker boot && \
        python3 -m ensurepip && \
        rm -r /usr/lib/python*/ensurepip && \
        pip3 install --upgrade pip==19.2.3 && \
        if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
        rm -r /root/.cache

RUN pip install \
        setuptools==${SETUPTOOLS_VERSION} \
        invoke==${INVOKE_VERSION} \
        pylint==${PYLINT_VERSION} \
        yamllint==${YAMLLINT_VERSION} && \
    echo "gem: --no-document" > /etc/gemrc && \
    gem install \
        inspec-bin:${INSPEC_VERSION} && \
    curl -SLO https://github.com/hadolint/hadolint/releases/download/v${HADOLINT_VERSION}/hadolint-Linux-x86_64 && \
    chmod +x hadolint-Linux-x86_64 && \
    mv hadolint-Linux-x86_64 /usr/local/bin/hadolint && \
    gem cleanup && \
    rm -rf /usr/lib/ruby/gems/*/cache/* \
           /tmp/* && \
    apk del build-dependencies

COPY ./hooks/environment.sh /buildkite/hooks/environment.sh
RUN  chmod +x /buildkite/hooks/environment.sh

VOLUME /buildkite
WORKDIR /buildkite
ENTRYPOINT ["buildkite-agent"]
CMD ["start"]
